In [1]:
import pandas as pd
import json 
import os

In [2]:
def read_first_json_file(directory_path):
    for filename in os.listdir(directory_path):
        if filename.endswith('.json'):
            filepath = os.path.join(directory_path, filename)
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
            return data, filename
    return None, None

data, filename = read_first_json_file('../json_file')
if data:
    df = pd.DataFrame(data)
    df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   video_id       30 non-null     object
 1   channel_title  30 non-null     object
 2   title          30 non-null     object
 3   description    30 non-null     object
 4   published_at   30 non-null     object
 5   comments       30 non-null     object
 6   statistics     30 non-null     object
dtypes: object(7)
memory usage: 1.8+ KB

In [3]:
display(df.head())

,video_id,channel_title,title,description,published_at,comments,statistics
0,Wmy5TQQPQho,Trực Tiếp Game,TÔI LÀM NHÂN VIÊN KIỂM DỊCH: PHÁT HIỆN ZOMBIE ...,Đây là video chơi game Quarantine Zone The Las...,2025-05-27T16:31:12Z,"[{'text': '❤', 'author': '@rockyjohnson2511', ...","{'viewCount': '312665', 'likeCount': '7541', '..."
1,G5lS6O7j4RI,Trực Tiếp Game,GAME GIẢ LẬP BÁN XE CŨ... NÁT NHƯ CHÁO CHÓ &am...,Đây là video chơi game Car Dealer Simulator tr...,2025-05-30T17:48:58Z,"[{'text': 'In Game, vua của mọi nghề 😅😅', 'aut...","{'viewCount': '197484', 'likeCount': '5620', '..."
2,46B-rfCAW4E,Trực Tiếp Game,"ĐỪNG MỞ CỬA, MỤ ẤY LÀ QUÁI VẬT ĐẤY !!! GAME KI...",Đây là video chơi game BrokenLore DON'T WATCH ...,2025-05-07T16:31:18Z,[{'text': 'Trời tiếng game giống tiếng chuông ...,"{'viewCount': '361042', 'likeCount': '8400', '..."
3,w-Ed_FP_Jbw,Trực Tiếp Game,CHƠI THỬ GAME KINH DỊ VIỆT NAM - ĐỒNG CỎ LAU !...,Đây là video chơi game ĐỒNG CỎ LAU (Demo 2) tr...,2025-04-13T16:11:01Z,[{'text': 'Đệt đang ăn cơm coi 17:07 thấy cơm ...,"{'viewCount': '397265', 'likeCount': '9805', '..."
4,u1wM5l5nyYw,Trực Tiếp Game,HÉ LỘ DỰ ÁN CHẾT YỂU: THẦN TRÙNG 2...,Đây là video chơi game trên kênh Trực Tiếp Gam...,2025-05-21T18:27:46Z,[{'text': 'Khởi động lại Alan Wake 2 đi anh ơi...,"{'viewCount': '284958', 'likeCount': '7285', '..."

In [4]:
stat_df = pd.json_normalize(df['statistics'])
display(stat_df)

   viewCount likeCount dislikeCount commentCount
0     312665      7541            0          249
1     197484      5620            0          130
2     361042      8400            0          167
3     397265      9805            0          496
4     284958      7285            0          281
5     268424      7133            0          187
6     446595      9055            0          216
7     331554      6823            0          202
8         10         0            0            0
9     394489      8233            0          410
10    121946      2231            0          387
11    251062      5934            0          205
12    244517      5265            0          234
13    286866      6215            0          217
14     40248       976            0           29
15     30484       847            0           55
16    371270      8475            0          215
17    356898      6564            0          312
18    461171     10085            0          237
19    407446      8456            0          445
20    673939     16159            0          214
21    419501      9380            0          232
22   1263063     21110            0         1055
23    479299      9828            0          262
24    310801      7808            0          179
25    291386      8103            0          300
26    437935      9758            0          161
27    630402     13489            0          829
28    354829      8284            0          535
29      4116        69            0            7

In [5]:
df1 = pd.concat([df.drop(columns=['statistics']), stat_df], axis=1)
df1 = df1.drop(columns=['comments', 'dislikeCount',  'description']).reset_index(drop=True)
df1['likeCount'] = pd.to_numeric(df1['likeCount'], errors='coerce')
df1['datetime'] = pd.to_datetime(df1['published_at'])
df1['date'] = df1['datetime'].dt.date
df1['time'] = df1['datetime'].dt.time
sorted_df1 = df1.sort_values(by='likeCount', ascending=False).reset_index(drop=True)

cleaned_stats_df = df1.drop(columns=['published_at'])
cleaned_stats_df = cleaned_stats_df.drop(columns='datetime')
cleaned_stats_df.to_csv('../data/statistics.csv', index=False)
display(cleaned_stats_df)

,video_id,channel_title,title,viewCount,likeCount,commentCount,date,time
0,Wmy5TQQPQho,Trực Tiếp Game,TÔI LÀM NHÂN VIÊN KIỂM DỊCH: PHÁT HIỆN ZOMBIE ...,312665,7541,249,2025-05-27,16:31:12
1,G5lS6O7j4RI,Trực Tiếp Game,GAME GIẢ LẬP BÁN XE CŨ... NÁT NHƯ CHÁO CHÓ &am...,197484,5620,130,2025-05-30,17:48:58
2,46B-rfCAW4E,Trực Tiếp Game,"ĐỪNG MỞ CỬA, MỤ ẤY LÀ QUÁI VẬT ĐẤY !!! GAME KI...",361042,8400,167,2025-05-07,16:31:18
3,w-Ed_FP_Jbw,Trực Tiếp Game,CHƠI THỬ GAME KINH DỊ VIỆT NAM - ĐỒNG CỎ LAU !...,397265,9805,496,2025-04-13,16:11:01
4,u1wM5l5nyYw,Trực Tiếp Game,HÉ LỘ DỰ ÁN CHẾT YỂU: THẦN TRÙNG 2...,284958,7285,281,2025-05-21,18:27:46
5,nP73z-EJjJQ,Trực Tiếp Game,GAME GIẢ LẬP LÁI TAXI ĐÊM GẶP MA !!! EM NÓ NGỒ...,268424,7133,187,2025-05-18,18:17:50
6,U6pwzBUOQ_I,Trực Tiếp Game,OAN HỒN #1: SỞN TÓC GÁY VỚI GAME KINH DỊ TỚI T...,446595,9055,216,2025-04-17,16:47:48
7,qPxs8zX7q-0,Trực Tiếp Game,NỮ SINH SỐNG SÓT GIỮA BẦY ZOMBIE KHÁT MÁU !!! ...,331554,6823,202,2025-05-11,17:05:24
8,g9hX4zCz1Og,Live Stream Game VietNam,🔴 LIVE Gym 🔴 Trực Tiếp Game Hôm Nay 2025,10,0,0,2025-05-30,00:18:15
9,pMHrbRweb6M,Trực Tiếp Game,CHƠI THỬ GAME BOM TẤN ỨNG VIÊN GOTY 2025 ĐANG ...,394489,8233,410,2025-04-29,05:49:47
10,rlJWXmZCCDE,BattleCharacterVNShort,Trực Tiếp Game vs Mixigaming #battleVNcharacte...,121946,2231,387,2023-08-22,15:01:11
11,CAzS_soXk4s,Trực Tiếp Game,ĐẾN QUỶ DỮ CŨNG PHẢI KHÓC THÉT !!! CHƠI THỬ GA...,251062,5934,205,2025-05-15,16:53:54
12,KUOyHE7f6aA,Trực Tiếp Game,"GAME NÀY BOSS KHỦNG NHƯ GOD OF WAR, TÔI THỰC S...",244517,5265,234,2025-05-04,17:17:09
13,-1ta-B1lA3s,Trực Tiếp Game,OAN HỒN #2 END: BI KỊCH NỮ SINH BỊ QUAY TRỘM V...,286866,6215,217,2025-04-20,19:02:09
14,RjZc2kAuZlE,Phú,Sếp Dũng CT và lò luyện thi cấp tốc | Trực Tiế...,40248,976,29,2022-10-27,10:04:27
15,wrXf-5OZ4Bo,TTG Gaming,con ma kiên nhẫn nhất quả đất =))) cre:Trực Ti...,30484,847,55,2025-02-14,15:29:07
16,ojG2MtVBvxo,Trực Tiếp Game,KIM TỰ THÁP MA ÁM &amp; TIKTOKER THỦY TỔ !!! A...,371270,8475,215,2025-01-22,17:09:42
17,b37bdtitay0,Trực Tiếp Game,KINGDOM COME: Deliverance 2 #7: 5 TIẾNG TRY HA...,356898,6564,312,2025-03-02,19:47:15
18,zQpNa1VImS0,Trực Tiếp Game,TÊN SÁT NHÂN NÀY CÓ THẬT NGOÀI ĐỜI !? LÂU LẮM ...,461171,10085,237,2024-12-05,17:05:14
19,nwKHE6M5tQk,Trực Tiếp Game,ASSASSIN&#39;S CREED SHADOWS #1: SAMURAI DA MÀ...,407446,8456,445,2025-03-19,17:06:55
20,V6DewUcZzKQ,Trực Tiếp Game,GAME RÙNG RỢN BUỒN CƯỜI GẤP 10 LẦN GAME HÀI !!...,673939,16159,214,2020-06-24,16:41:34
21,7aJnShgDJcA,Trực Tiếp Game,(Kinh dị) TÔI LÀM TESTER CHO TRÒ CHƠI BỊ QUỶ Á...,419501,9380,232,2024-12-17,17:58:32
22,zJyCGyoAKlM,Trực Tiếp Game,TAI ƯƠNG - CHƠI THỬ GAME KINH DỊ ĐẸP NHẤT CỦA ...,1263063,21110,1055,2024-10-23,18:28:10
23,GCp8X2o3tQc,Trực Tiếp Game,Fears to Fathom - Woodbury Getaway #1: THUÊ NH...,479299,9828,262,2024-09-17,09:02:25
24,gLilIX5jtLY,Trực Tiếp Game,THỬ CHƠI GAME KINH DỊ Ở MỨC KHÓ CAO NHẤT &amp;...,310801,7808,179,2025-01-14,16:25:22
25,1Jjj_bitQyA,Trực Tiếp Game,Stigmatized Property #1: PHÒNG TRỌ MA ÁM VÀ CH...,291386,8103,300,2020-06-30,03:00:00
26,JYSq80P6C3o,Trực Tiếp Game,GAME GIẢ LẬP ĐỨA CON MẤT DẠY =)))) BỐ MẸ CHÂU ...,437935,9758,161,2025-01-07,17:11:37
27,E9j-Rf6aShI,Trực Tiếp Game,STREAMER BỊ VIEWER SÁT HẠI !!! GAME KINH DỊ MỚ...,630402,13489,829,2023-08-27,15:34:00
28,HAN2BYH53d8,Trực Tiếp Game,CHUYẾN TÀU MA QUỶ !!! GAME KINH DỊ VIỆT HÓA MỚ...,354829,8284,535,2024-03-23,17:37:01
29,GHJOAA5Trh8,TTG Gaming,người làm chó hưởng=))) cre:Trực Tiếp Game #du...,4116,69,7,2025-05-11,08:44:43