In [6]:
import pandas as pd
from textblob import TextBlob

In [7]:
df = pd.read_csv('../data/comments.csv')
df2 = pd.read_csv('../data/statistics.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   video_id  143 non-null    object
 1   comments  142 non-null    object
 2   date      143 non-null    object
 3   time      143 non-null    object
dtypes: object(4)
memory usage: 4.6+ KB

In [8]:

def comments_sentiment(text):
    blob = TextBlob(str(text))
    polarity = blob.sentiment.polarity
    if polarity > 0.1:
        return 'positive'
    elif polarity < -0.1:
        return 'negative'
    else:
        return 'neutral'
    
df['comments'] = df['comments'].apply(comments_sentiment)
df.to_csv('../data/comments_sentiments.csv', index=False)
display(df)

        video_id  comments        date      time
0    zsjvFFKOm3c  negative  2021-04-06  14:47:25
1    zsjvFFKOm3c   neutral  2021-04-06  14:47:25
2    zsjvFFKOm3c   neutral  2021-04-06  14:47:25
3    zsjvFFKOm3c  negative  2021-04-06  14:47:25
4    zsjvFFKOm3c   neutral  2021-04-06  14:47:25
..           ...       ...         ...       ...
138  l8DCPaHc5TQ  positive  2022-08-23  08:00:15
139  l8DCPaHc5TQ  positive  2022-08-23  08:00:15
140  l8DCPaHc5TQ   neutral  2022-08-23  08:00:15
141  l8DCPaHc5TQ  positive  2022-08-23  08:00:15
142  l8DCPaHc5TQ  positive  2022-08-23  08:00:15

[143 rows x 4 columns]

In [9]:
df3 = pd.read_csv('../data/comments_sentiments.csv')

df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   video_id  143 non-null    object
 1   comments  143 non-null    object
 2   date      143 non-null    object
 3   time      143 non-null    object
dtypes: object(4)
memory usage: 4.6+ KB

In [10]:
def sentiment_percentages(group):
    total = len(group)
    positive = (group == 'positive').sum() / total * 100
    negative = (group == 'negative').sum() / total * 100
    neutral = (group == 'neutral').sum() / total * 100
    return pd.Series({
        'positive_pct': positive,
        'negative_pct': negative,
        'neutral_pct': neutral,
        'total_comments': total
    })


sentiment_summary = df3.groupby('video_id')['comments'].apply(sentiment_percentages).reset_index()

df_merged = df2.merge(sentiment_summary, on='video_id', how='left')

df_merged['engagement_stats'] = (
    df_merged['viewCount'] * 0.1 + df_merged['likeCount'] * 1 + df_merged['commentCount'] * 2
)

df_wide = df_merged.pivot_table(
    index=['video_id', 'channel_title', 'title', 'viewCount', 'likeCount', 'commentCount', 'date', 'time'],
    columns='level_1',
    values='comments'
).reset_index()

cleaned_sentiment = df_wide[df_wide['total_comments'] > 1.0]
cleaned_sentiment = df_wide.drop(columns=['channel_title', 'title'])

cleaned_sentiment.to_csv('../data/sentiment.csv', index=False)
display(cleaned_sentiment.head(100))

level_1,video_id,viewCount,likeCount,commentCount,date,time,negative_pct,neutral_pct,positive_pct,total_comments
0,27axs9dO7AE,2111131,51484,1391,2019-04-16,13:53:16,0.0,60.0,40.0,5.0
1,2i7YhEjo1Jw,103414,8198,23,2023-07-20,12:45:33,20.0,60.0,20.0,5.0
2,3s0lFtUrhSQ,114482,2512,38,2023-07-29,06:57:08,0.0,60.0,40.0,5.0
3,7S_tz1z_5bA,12948455,270389,9772,2019-03-20,00:50:32,20.0,20.0,60.0,5.0
4,7mz73uXD9DA,794690,23458,865,2024-03-11,10:00:11,20.0,60.0,20.0,5.0
5,9ctKDYilxkU,12202,819,2,2024-03-18,14:25:26,0.0,100.0,0.0,2.0
6,Ah_LMYqd2CE,5721078,233245,12955,2025-02-22,00:18:28,20.0,20.0,60.0,5.0
7,Cz3WcZLRaWc,1057320,35199,1528,2021-04-16,15:41:25,0.0,40.0,60.0,5.0
8,HXV3zeQKqGY,19673794,365172,11646,2018-07-02,17:13:32,0.0,60.0,40.0,5.0
9,HZ5eTsH3_TM,180858,17868,61,2023-03-21,00:21:41,0.0,40.0,60.0,5.0
10,OT1RErkfLNQ,625655,14272,551,2024-10-08,12:00:27,0.0,100.0,0.0,5.0
11,SSKVgrwhzus,333078,11823,1003,2025-03-27,13:00:28,0.0,40.0,60.0,5.0
12,T_Bt-iwojCc,100382,3099,14,2023-10-12,14:23:34,20.0,80.0,0.0,5.0
13,WA_OlHzqoz8,57483,6166,16,2023-11-06,14:28:03,0.0,60.0,40.0,5.0
14,Yh4CrPHVBdE,355404,9416,246,2023-07-24,03:58:42,0.0,60.0,40.0,5.0
15,cTNcvAoFr9Q,43968,4183,30,2024-07-05,14:11:47,0.0,60.0,40.0,5.0
16,ctK-M3jGTPU,135790,3573,73,2023-05-28,15:23:54,0.0,60.0,40.0,5.0
17,grFLGgArdd4,152684,14879,52,2024-12-07,03:55:18,0.0,80.0,20.0,5.0
18,h0nxCDiD-zg,2531998,46702,1644,2022-03-22,07:00:11,0.0,20.0,80.0,5.0
19,jb1dNbU0jtI,374,2,0,2025-05-27,19:18:55,0.0,100.0,0.0,1.0
20,kbKty5ZVKMY,2584268,62532,1166,2020-11-11,17:09:30,0.0,40.0,60.0,5.0
21,l8DCPaHc5TQ,1286740,41174,922,2022-08-23,08:00:15,0.0,20.0,80.0,5.0
22,m0FQSFZG76s,66586,2570,20,2023-08-25,09:46:44,0.0,80.0,20.0,5.0
23,pwmynHnr704,37102,2685,29,2024-11-13,13:42:01,20.0,40.0,40.0,5.0
24,qa_0Qx41qQI,250220,9852,93,2023-09-25,16:23:09,20.0,40.0,40.0,5.0
25,s84B-Wa76Ps,163084,5358,16,2024-03-26,12:30:39,0.0,60.0,40.0,5.0
26,tk5SB8jiK7U,435590,10184,201,2024-05-14,13:15:10,0.0,60.0,40.0,5.0
27,xiUTqnI6xk8,1802668,55427,1933,2022-08-17,16:07:03,0.0,20.0,80.0,5.0
28,yMqldbY2AAg,638205,20185,180,2024-04-03,15:31:51,0.0,80.0,20.0,5.0
29,zsjvFFKOm3c,1117031,38758,611,2021-04-06,14:47:25,40.0,60.0,0.0,5.0